on:
  push:
    branches:
      - main

name: Build and Deploy
env:
  REACT_APP_API_BASE_URL: /api
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Environment variables setup
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_REACT_APP_GITHUB_CLIENT_ID: ${{ secrets.REACT_APP_GITHUB_CLIENT_ID }}
          envkey_REACT_APP_GITHUB_REDIRECT_URI: ${{ secrets.REACT_APP_GITHUB_REDIRECT_URI }}
          envkey_REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}
          file_name: .env
          fail_on_empty: true

      - name: Build
        run: docker-compose build

      - name: Run
        run: docker-compose down && docker-compose up
